refactor(module): use `extendBuild`
nuxt-community/separate-env-module pull request #25
Opened 2019-02-27 20:49 UTC by ricardogobbosouza

Resolves #5

2019-02-27 21:06 UTC, TheAlexLichter requested changes

2019-02-27 21:06 UTC, manniL commented on test/module.test.js
> -  test('honor custom build.extend function', async () => {
I'd still keep that test

2019-02-28 09:48 UTC, ricardogobbosouza commented
@manniL Actually I think we can not apply `extendBuild` here because the` build.extend` function is called before, ie its values are overwritten and in the case it should be the other way around

2019-02-28 09:54 UTC, manniL commented
@ricardogobbosouza Not sure why that should be a problem. Ideally, the `separate-env` module is called at the end so all env values that have been "created" before could be separated properly.

Or am I missing a point here?

2019-02-28 10:03 UTC, ricardogobbosouza commented
@manniL If you look for the test `honor custom build.extend function`
https://github.com/nuxt-community/separate-env-module/blob/master/test/module.test.js#L85 should the `ONLY_SERVER` variable be` yup` or `nope`?

2019-02-28 10:57 UTC, manniL commented
@ricardogobbosouza `nope`

2019-02-28 11:22 UTC, ricardogobbosouza commented
@manniL So we have a problem, why today `separate-env` is called first of all https://github.com/nuxt-community/separate-env-module/blob/master/lib/module.js#L36 with` extendBuild he will be called in sequence

2019-02-28 13:56 UTC, ricardogobbosouza commented
In my opinion we can not apply `extendBuild` here

2019-02-28 13:56 UTC, ricardogobbosouza commented
@manniL In my opinion we can not apply `extendBuild` here

2019-03-08 12:48 UTC, ricardogobbosouza commented
@manniL 

Today we can not define the `extendBuid` order
https://github.com/nuxt/nuxt.js/blob/dev/packages/core/src/module.js#L104

And in this case we need to do so:
```js
this.options.build.extend = chainFn(fn, this.options.build.extend)
```
The `separate-env` should be the last.

2019-03-08 12:58 UTC, manniL commented
Yeah, you are right :relaxed:

2019-03-08 12:58 UTC, closed without merging